-- 滴滴券相关
ALTER TABLE `vps_sys_ticket_info`
MODIFY COLUMN `TICKET_TYPE`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '优惠券类型：0链接，1券码，2图片，3动态券码，4活动编码' AFTER `TICKET_MONEY`;

INSERT INTO vps_sys_ticket_category_info VALUES('9982f054-a18b-11ea-8b2e-6e6d36e3ad65', 'K', '滴滴券', '滴滴优惠券', '0', NOW(), '1', NOW(), '1');
INSERT INTO vps_sys_ticket_info VALUES(UUID(), '9982f054-a18b-11ea-8b2e-6e6d36e3ad65', 'KN001', '滴滴代驾券-5元', '5.00', '4', '活动编码', '0', NOW(), '1', NOW(), '1');

ALTER TABLE `vps_vcode_ticket_user_record_1` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_2` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_3` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_4` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_5` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_6` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_7` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_8` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_9` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_10` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_11` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;
ALTER TABLE `vps_vcode_ticket_user_record_12` ADD COLUMN `VCODE_ACTIVITY_KEY`  varchar(36) NULL DEFAULT NULL COMMENT '扫码活动KEY' AFTER `INFO_KEY`, ADD COLUMN `PHONE_NUMBER`  varchar(11) NULL DEFAULT NULL COMMENT '领取手机号' AFTER `USER_KEY`;


