-- 增加首扫限制
ALTER TABLE `vps_vcode_activity_rebate_rule_cog`
ADD COLUMN `RESTRICT_FIRST_DAY_BOTTLE`  int(11) NULL DEFAULT 0 COMMENT '每日首扫个数' AFTER `UPDATE_USER`,
ADD COLUMN `RESTRICT_FIRST_DAY_MONEY`  decimal(20,2) NULL DEFAULT 0.00 COMMENT '每日首扫金额' AFTER `RESTRICT_FIRST_DAY_BOTTLE`,
ADD COLUMN `RESTRICT_FIRST_MONTH_BOTTLE`  int(11) NULL DEFAULT 0 COMMENT '每月首扫个数' AFTER `RESTRICT_FIRST_DAY_MONEY`,
ADD COLUMN `RESTRICT_FIRST_MONTH_MONEY`  decimal(20,2) NULL DEFAULT 0.00 COMMENT '每月首扫金额' AFTER `RESTRICT_FIRST_MONTH_BOTTLE`,
ADD COLUMN `RESTRICT_FIRST_TOTAL_BOTTLE`  int(11) NULL DEFAULT 0 COMMENT '首扫总个数' AFTER `RESTRICT_FIRST_MONTH_MONEY`,
ADD COLUMN `RESTRICT_FIRST_TOTAL_MONEY`  decimal(20,2) NULL DEFAULT 0.00 COMMENT '首扫总金额' AFTER `RESTRICT_FIRST_TOTAL_BOTTLE`,
ADD COLUMN `RESTRICT_FIRST_TIME`  datetime NULL DEFAULT NULL COMMENT '首扫标记' AFTER `RESTRICT_FIRST_TOTAL_MONEY`;


-- 阶梯备注
ALTER TABLE `vps_ladder_rule_cog`
ADD COLUMN `remarks`  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注' AFTER `ALLOWANCEA_EXCLUSIVE_FLAG`;
