
-- ★★★ 各省区数据库执行
-- 消费者账户表增加过期金额及过期积分字段
ALTER TABLE `vps_consumer_account_info` 
ADD COLUMN `EXPIRE_VPOINTS` bigint(20) NULL DEFAULT 0 COMMENT ' 将过期积分' AFTER `SURPLUS_VPOINTS`,
ADD COLUMN `EXPIRE_MONEY` decimal(20, 2) NULL DEFAULT 0 COMMENT '将过期金额' AFTER `FREEZE_MONEY`;

-- 过期 记录表
CREATE TABLE vps_consumer_account_expire_record_2020 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2021 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2022 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2023 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2024 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2025 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2026 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2027 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2028 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';
CREATE TABLE vps_consumer_account_expire_record_2029 ( INFO_KEY varchar(36) NOT NULL COMMENT '主键', USER_KEY varchar(36) DEFAULT NULL COMMENT '用户主键', PRIZE_TYPE varchar(2) DEFAULT NULL COMMENT '奖项类型：0现金红包, 1积分红包, 2现金积分红包', EXPIRE_MONEY decimal(20,2) DEFAULT NULL COMMENT '过期金额', EXPIRE_VPOINTS int(11) DEFAULT '0' COMMENT '过期积分', EXPIRE_TIME datetime DEFAULT NULL COMMENT '过期时间', PRIMARY KEY (INFO_KEY), KEY INDEX_USER_KEY (USER_KEY) USING BTREE, KEY idx_expire_time (EXPIRE_TIME) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消费者账户过期记录表';

-- 功能开关
insert into vps_sys_datadic_m values ('815c0933-0dbb-11eb-b458-6e6d36e3ad65','62ce64bd-4cb6-11ea-b627-6e6d36e3ad65', 'switch_consumerAccount_expire', '0', '过期金额及积分开关', '功能开关配置- 0关 1开', 21, '0', 1, NOW(), '1', NOW(), '1');

-- ★★★ saas_db_main库增加job配置
INSERT INTO `saas_db_main`.`vps_sys_datadic_m`(`DATADIC_KEY`, `CATEGORY_KEY`, `DATA_ID`, `DATA_VALUE`, `DATA_ALIAS`, `DATA_EXPLAIN`, `SEQUENCE_NUM`, `DELETE_FLAG`, `VERSION`, `CREATE_TIME`, `CREATE_USER`, `UPDATE_TIME`, `UPDATE_USER`) 
VALUES ('1f4ba36s-5df7-11ea-b54f-6e6d36e3ad65', '1642eb1a-5485-11ea-ba2a-6e6d36e3ad65', 'consumer_account_info_expire', 'hebei', '接口：消费者账户过期金额及积分job', '接口：消费者账户过期金额及积分job', 1, '0', 1, '2020-09-24 17:04:15', '1', '2020-09-24 17:04:15', '1');

-- xxl-job
执行器：接口
路由策略：第一个
任务描述：消费者账户过期金额及积分job
Cron：0 0 0 1 7 ?
jobHander：consumerAccountExpireJobHandler