-- 各省区数据库执行
ALTER TABLE `vps_consumer_account_info`
ADD COLUMN `TOTAL_EXPIRE_VPOINTS`  bigint(20) NULL DEFAULT 0 COMMENT '累计过期积分' AFTER `EXPIRE_VPOINTS`,
ADD COLUMN `TOTAL_EXPIRE_MONEY`  decimal(20,2) NULL DEFAULT 0.00 COMMENT '累计过期金额' AFTER `EXPIRE_MONEY`;
